branch-defaults:
  default:
    environment: udagram-app-dev
environment-defaults:
  Udagramapp-env-1:
    branch: null
    repository: null
global:
  application_name: udagram-app
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  deploy:
    artifact: www/Archive.zip
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
  deploy:
    artifact: www/Archive.zip