  # بسم الله الرحمن الرحيم
  version: 2.1
  orbs:
    # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
    node: circleci/node@5.0.2
    #browser-tools: circleci/browser-tools@1.2.3
    #aws-cli: circleci/aws-cli@3.1.0
    #eb: circleci/aws-elastic-beanstalk@1.0.0
    # different jobs are calles later in the workflows sections
  jobs:
    build:
      docker:
        # the base image can run most needed actions with orbs
        - image: "cimg/base:stable"
        # - image: cimg/node:16.13.1-browsers

      steps:
        - node/install
        - checkout
      #  - aws-cli/setup
      #  - eb/setup
        # Api Install
        - run: 
            name: API Install
            command: |
             npm run api:install
        # Api build
        - run: 
            name: API build
            command: |
             npm run api:build
        # FRONT END Install
        - run: 
            name: Api Deploy
            command: echo POSTGRES_DB
              