  version: 2.1
  orbs:
    # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
    node: circleci/node@5.0.2
    browser-tools: circleci/browser-tools@1.2.3

    # different jobs are calles later in the workflows sections
  jobs:
    build:
      docker:
        # the base image can run most needed actions with orbs
        - image: "cimg/base:stable"
        # - image: cimg/node:16.13.1-browsers

      steps:
        - browser-tools/install-chrome
        - browser-tools/install-chromedriver
        - node/install
        - checkout
        
        # install dependencies in both apps
        - run:
            name: First
            command: |
              echo "بسم الله الرحمن الرحيم"
        # BACK END INSTALLATION
        - run: 
            name: API Install
            command: |
              npm run api:install
        # BACK END build
        - run: 
            name: API BUILD
            command: |
              npm run api:build
        # FRONT END INSTALLATION
        - run: 
            name: Front-End Install
            command: |
              npm run frontend:install
        # FRONT END BUILD
        - run: 
            name: Front-End BUILD
            command: |
              npm run frontend:build
        # FRONT END test
        - run: 
            name: Front-End test
            command: |
              npm run frontend:test
        # FRONT END lint
        - run: 
            name: Front-End lint
            command: |
              npm run frontend:lint
        # FRONT END e2e
        - run: 
            name: Front-End e2e
            command: |
              npm run frontend:e2e
              